import psutil
#______________________获取CPU相关______________#
print(psutil.cpu_times())
#查看cpu完整信息，获取单项信息
print(psutil.cpu_count())
#查看cpu逻辑个数
print(psutil.cpu_coutnt(logical=False))
#查看cpu物理个数
print(psutil.cpu_percent(interval=0))
#查看单个cpu的使用率
print(psutil.cpu_percent(percpu=True))
#查看每个cpu的使用率
#___________________获取内存d相关信息——————————#
print(psutil.virtual_memory())
#查看内存完整信息
print(psutil.virtual_memory().percent)
#查看内存使用百分比
print(psutil.swap_memory())
#查看swap分区的完整信息
#________________获取硬盘分区相关信息———————————————#
print(psutil.disk_usage('D:\\'))
#获取硬盘的使用情况
print(psutil.disk_io_countriest(perdisk=True))
#查看硬盘的读写状况
#__________________获取网络相关信息——————————————————#
print(psutil.net_io_counters())
#获取网络的总体信息
print(psutil.net_io_counters(pernic=True))
#获取每个网卡的IO信息
print(psutil.net_if_addrs())
#获取网卡相关地址信息
print(psutil.net_connections())
#获取所有接口的连接信息
#——————————————获取系统其他相关信息————————————————#
print(psutil.users())
#获取当前登录信息
print(datetime.datetime.fromtimestamp(psutil.boot_time()).strftime('%Y-%m-%d %H:%M:%S'))
#获取开机时间